### PR TITLE
Added Pro Git and Turing Way as reading

### PR DESCRIPTION
**Pull request by jbteves**
Links out to non-SFIM resources.

### CODE REVIEW

**Comment by jbteves** [comment]
@andrewtmorgan I've requested a review from you so you can get practice with the GitHub UI if you have time, but if not then there's no worries.

**Comment by jbteves** [comment]
@handwerkerd please let me know if you think we should be adding more details for the recommended reading specifically, or if we've missed something.

**Review by handwerkerd — COMMENTED** [review]
I'm fine with creating this page and adding more content later. The other things we've already discussed are: http://swcarpentry.github.io/git-novice/ and some Coursera classes.

**Comment by jbteves** [comment]
Good catch on software carpentry, adding.

**Review by andrewtmorgan — APPROVED** [review]
### Thanks Josh!
This was helpful to understand how to access reviews in github.

**Comment by jbteves** [comment]
Excellent, thanks! Sometime when I have a more substantive PR we can walk through the various features.

**Pull request merged**
